### ISSUE TITLE
Line-length issue conflicting with flake8

### ISSUE THREAD

**Issue by Remi-Gau** [adamchainz/blacken-docs#294]
### Python Version

3.11.3

### Package Version

1.16.0

### Description

I checked passed issues and I could not find someone having the same problem so here we.

Here is how to reproduce.

Create a new empty git repo and add 2 files in.

A python file with one line in the doc string that goes beyond the flake8 default line length:

```python
"""Demo."""


def foo(a):
    """Print a.

    :param a: some parameter

    .. code-block:: python

        a = ["lore", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing"]
        foo(1)

    """
    print(a)
```

This pre-commit config to run black, blacken-doc, flake8 where all have the same line length

```yml
repos:

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
        args: [--line-length, "79"]
        additional_dependencies:
        -   black==23.9.1

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--line-length, "79"]

-   repo: https://github.com/pyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
```

Run pre-commit

```bash
$ pre-commit run -a

blacken-docs.............................................................Passed
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

foo.py:11:80: E501 line too long (82 > 79 characters)
```

If I try to change the line to pacify flake8 with for example:

```python
"""Demo."""


def foo(a):
    """Print a.

    :param a: some parameter

    .. code-block:: python

        a = ["lore", "ipsum", "dolor", "sit", "amet", "consectetur", 
             "adipiscing"]
        foo(1)

    """
    print(a)
```

Then blacken-docs does its job and puts everything on a single and then flake8 complains again.

Any suggestion on how to deal with this?
